# Generated by Django 3.0.5 on 2020-12-06 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20201204_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(blank=True, choices=[('r', 'Reading now'), ('a', 'Already read'), ('w', 'Want to read')], default='w', max_length=1),
        ),
    ]
