# Generated by Django 3.0.5 on 2020-12-06 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20201206_1841'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': (('perm_test', 'Permission test'),)},
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(blank=True, choices=[('w', 'Want to read'), ('a', 'Already read'), ('r', 'Reading now')], default='w', max_length=1),
        ),
    ]
